### PR TITLE
Create pypi workflow action

### PR DESCRIPTION
**Pull request by gsheni**

### CODE REVIEW

**Comment by rwedge** [comment]
Can you also remove the old workflow file and the now unused `release` folder?

**Comment by gsheni** [comment]
> Can you also remove the old workflow file and the now unused `release` folder?

done

**Comment by rwedge** [comment]
Can you also delete the `release` folder the old action used?

**Comment by gsheni** [comment]
> Can you also delete the `release` folder the old action used?

sorry about that. fixed. removed the folder and the old workflow

**Pull request merged**
